'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { UiTypography as UiTypographyElement, defineCustomElement as defineUiTypography } from "core-library/dist/components/ui-typography.js";
import React from 'react';

export type UiTypographyEvents = NonNullable<unknown>;

export const UiTypography: StencilReactComponent<UiTypographyElement, UiTypographyEvents> = /*@__PURE__*/ createComponent<UiTypographyElement, UiTypographyEvents>({
    tagName: 'ui-typography',
    elementClass: UiTypographyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiTypographyEvents,
    defineCustomElement: defineUiTypography
});
