'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { UiButton as UiButtonElement, defineCustomElement as defineUiButton } from "core-library/dist/components/ui-button.js";
import { UiIcon as UiIconElement, defineCustomElement as defineUiIcon } from "core-library/dist/components/ui-icon.js";
import { UiLogo as UiLogoElement, defineCustomElement as defineUiLogo } from "core-library/dist/components/ui-logo.js";
import { UiTypography as UiTypographyElement, defineCustomElement as defineUiTypography } from "core-library/dist/components/ui-typography.js";
import React from 'react';

export type UiButtonEvents = NonNullable<unknown>;

export const UiButton: StencilReactComponent<UiButtonElement, UiButtonEvents> = /*@__PURE__*/ createComponent<UiButtonElement, UiButtonEvents>({
    tagName: 'ui-button',
    elementClass: UiButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiButtonEvents,
    defineCustomElement: defineUiButton
});

export type UiIconEvents = NonNullable<unknown>;

export const UiIcon: StencilReactComponent<UiIconElement, UiIconEvents> = /*@__PURE__*/ createComponent<UiIconElement, UiIconEvents>({
    tagName: 'ui-icon',
    elementClass: UiIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiIconEvents,
    defineCustomElement: defineUiIcon
});

export type UiLogoEvents = NonNullable<unknown>;

export const UiLogo: StencilReactComponent<UiLogoElement, UiLogoEvents> = /*@__PURE__*/ createComponent<UiLogoElement, UiLogoEvents>({
    tagName: 'ui-logo',
    elementClass: UiLogoElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiLogoEvents,
    defineCustomElement: defineUiLogo
});

export type UiTypographyEvents = NonNullable<unknown>;

export const UiTypography: StencilReactComponent<UiTypographyElement, UiTypographyEvents> = /*@__PURE__*/ createComponent<UiTypographyElement, UiTypographyEvents>({
    tagName: 'ui-typography',
    elementClass: UiTypographyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiTypographyEvents,
    defineCustomElement: defineUiTypography
});
